# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning Journey 
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is my part of learning journey, to note down the important points for the future reference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hnamitha1.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  hnamitha1

# Build settings
markdown: kramdown
